#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "invoiceshelf"
name = "InvoiceShelf"
description.en = "Invoicing Solution for Individuals & Businesses"
description.fr = "Solution de facturation pour les particuliers et les entreprises"

version = "2.1.1~ynh2"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "AGPL-3.0"
website = "https://invoiceshelf.com"
userdoc = "https://docs.invoiceshelf.com/"
code = "https://github.com/InvoiceShelf/InvoiceShelf"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/InvoiceShelf/InvoiceShelf/releases/download/2.1.1/InvoiceShelf.zip"
    sha256 = "16d5a16f2c342d08d4cdc0272d40a415a0ffaab2aaa38ddc7c8efdeb3ee15aef"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "InvoiceShelf.zip"

    [resources.system_user]
    allow_email = true
    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api/*"
    api.allowed = ["visitors", "all_users"]
    api.show_tile = false
    api.protected = true
    api.auth_header = true

    [resources.apt]
    packages = "postgresql, postgresql-contrib, redis-server, php8.3-pgsql, php8.3-bcmath, php8.3-curl, php8.3-dom, php8.3-mbstring, php8.3-tokenizer, php8.3-zip, php8.3-xml, php8.3-json, php8.3-exif, php8.3-gd, php8.3-pdo"

    [resources.database]
    type = "postgresql"
