#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/public/;

  index index.php;

  client_max_body_size 50M;

  # InvoiceShelf's default config, for reference:
  # https://github.com/InvoiceShelf/docker/blob/master/default.conf

  # serve static files directly
  location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
    access_log off;
    log_not_found off;
    autoindex off;
    # 86400 = 1 day
    more_set_headers "Cache-Control: private, immutable, max-age=86400";
  }

  location /build/assets/ {
    access_log off;
    log_not_found off;
    autoindex off;
    # 604800 = 1 week
    more_set_headers "Cache-Control: public, immutable, max-age=604800";
  }

  # removes trailing slashes (prevents SEO duplicate content issues)
  if (!-d $request_filename) {
    rewrite ^/(.+)/$ /$1 permanent;
  }

  # If the request is not for a valid file (image, js, css, etc.), send to bootstrap
  if (!-e $request_filename) {
    rewrite ^/(.*)$ /index.php?/$1 last;
    break;
  }

  try_files $uri $uri/ /index.php?$query_string;
  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_no_auth;
  }

  # Deny access to other .php files, rather than exposing their contents
  location ~ [^/]\.php(/|$) {
    return 403;
  }

}

# disabling the API point of the built-in updater (which can break the installation)
# so the user must update using the YNH package
location /api/v1/check/update {
  return 403 "<!DOCTYPE html><title>403 Forbidden</title><style>body{width:35em;margin:0 auto;font-family:Tahoma,Verdana,Arial,sans-serif}</style><h1>403 Forbidden</h1><p>InvoiceShelf's built-in update function is disabled by YunoHost.<p>You must update InvoiceShelf via YunoHost.<p>If the update is not yet available, please be patient. Thank you!";
  default_type text/html;
}
